---
sudo: required

# List of the OS'es that will be used for the test.
env:
  - distro: ubuntu1804
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: debian9
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: debian8
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: centos6
    init: /sbin/init
    run_opts: ""
  - distro: fedora29
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: fedoira28
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

# Configure Travis to use Docker
services:
  - docker

before_install:
  # Pull docker container
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - 'container_id=$(mktemp)'

  # Run container
  - 'docker run --detach --volume="${PWD}":/tmp/ansible/roles/ansible-role-os-upgrade:ro ${run_opts) kamikazestar/docker-${distro}-ansible:latest "${init}" > "${container_id}"'

  # Check Ansible syntax
  - 'docker exec --tty "$(cat ${container_id}" env TERM=xterm ansible-playbook /etc/ansible/roles/ansible-role-os-upgrade/tests/test.yml --syntax-check'

  # Test Ansible role
  - 'docker exec --tty "$(cat ${container_id}" env TERM=xterm ansible-playbook /etc/ansible/roles/ansible-role-os-upgrade/tests/test.yml'

  # Test role idempotence
  - 'idempotence=$(mktemp)'
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansivle/roles/ansible-role-os-upgrade/tests/test.yml | tee -a ${idempotence}'
  - 'tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: failed' && exit 1)'

  # TODO: Ensure that all updates are installed


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
