---
language: python
services: docker

branches:
  only:
    - master
    - develop

env:
  global:
    - ROLE_NAME: os-upgrade
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: fedora30
    - MOLECULE_DISTRO: fedora29
    # Line commented du to error while running image:
    # Failed to mount tmpfs at /run: Operation not permitted
    # Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
    # [!!!!!!] Failed to mount API filesystems, freezing.
    # - MOLECLUE_DISTRO: amazonlinux2
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME kamikazestar.$ROLE_NAME
  - cd kamikazestar.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
