---
- name: Upgrade OS
  apt:
    upgrade: "{{ debian_upgrade_type }}"
    update_cache: true
    cache_valid_time: 3600

- name: Perform autoremove after upgade
  apt:
    autoremove: "{{ debian_autoremove }}"

- name: Check that reboot is required
  shell: "[ -f /var/run/reboot-required ]"
  failed_when: false
  register: reboot_required
  changed_when: reboot_required.rc == 0
  notify: os_reboot
  