---
- name: Upgrade OS
  apt:
    upgrade: "{{ debian_upgrade_type }}"
    update_cache: true
    cache_valid_time: 3600

- name: Perform autoremove after upgade
  apt:
    autoremove: "{{ debian_autoremove }}"

- name: Check that reboot is required
  shell: cat /var/run/reboot-required
  failed_when: false
  register: reboot_required
  changed_when: false

- name: Reboot OS if required
  notify:
    - os_reboot
  when: reboot_required
