---
- name: Upgrade OS
  yum:
    name: '*'
    state: latest
  tags:
    - skip_ansible_lint

- name: Check that reboot is required
  shell: needs-restarting -r
  failed_when: false
  register: reboot_required
  changed_when: false
  notify: os_reboot
